Ft tasker quote response 133092183
andela/workdey pull request #118
Opened 2016-10-31 09:39 UTC by andela-vkironde

#### What does this PR do?
Create a table ```quotes```
Create a model for the table ```quotes```
Create a quote notification.
Create a view to capture Tasker response to a Quote
Create a view to show artisan information if the quote is accepted.

#### What are the relevant pivotal tracker stories?
133092183

#### Screenshots (if appropriate)
<img width="1916" alt="1" src="https://cloud.githubusercontent.com/assets/22389591/19849723/cde8da9a-9f65-11e6-8ebe-f943fa221a71.png">
<img width="1910" alt="2" src="https://cloud.githubusercontent.com/assets/22389591/19849722/cde86e20-9f65-11e6-8ec3-e724f4b4c921.png">
<img width="1920" alt="3" src="https://cloud.githubusercontent.com/assets/22389591/19849724/cdef1310-9f65-11e6-8125-c25e17827977.png">

2016-10-31 22:44 UTC, andela-fadebayo requested changes

2016-10-31 22:44 UTC, andela-fadebayo commented on app/assets/javascripts/quote_notification.js
> +      // console.log(data)
Remove `console.log`

2016-10-31 22:44 UTC, andela-fadebayo commented on app/assets/javascripts/quote_notification.js
> +      console.log(error)
Handle this error, probably display it to the user. Remove `console.log`

2016-10-31 22:44 UTC, andela-fadebayo commented on app/controllers/notifications_controller.rb
> +    @event_name = params[:event_name]
why is the params retrieved this way?

2016-10-31 22:44 UTC, andela-fadebayo commented on app/models/notification.rb
> +  def self.quote_notification(user)
What does this method do?

2016-10-31 22:44 UTC, andela-fadebayo commented on app/models/service.rb
> +class Service < ActiveRecord::Base
This looks like the same class in @andela-amagana PR. Did you merge his work here and will this result in conflict later?

2016-10-31 22:44 UTC, andela-fadebayo commented on app/views/notifications/index.html.erb
> +              <%if object.notifiable_type == 'Quote'%>
It's preferred to compare string in one case (either upcase or downcase). It's usually downcase. Compare `object.notifiable_type` against `quote` instead.

2016-10-31 22:44 UTC, andela-fadebayo commented on app/views/notifications/index.html.erb
> +              <%#= render partial: "show_information" %>
What is this else block meant to do? 
Remove comment.

2016-10-31 22:44 UTC, andela-fadebayo commented on app/views/notifications/index.html.erb
> -          <%#= render partial: "show_information" %>
Remove comment if not used.

2016-10-31 22:44 UTC, andela-fadebayo commented on app/views/notifications/index.html.erb
> +                  <button id='quote_accept' class="btn teal modal-action" onclick="quotation('accepted',<%=object.notifiable.id%>)">Accept</button>
There should be appropriate spacing, like so
`onclick="quotation('accepted', <%= object.notifiable.id %>)"`
here and other places.

2016-10-31 22:44 UTC, andela-fadebayo commented on spec/factories/services.rb
> +    title "MyString"
`MyString` is the title of this service?

2016-10-31 22:44 UTC, andela-fadebayo commented on spec/features/share_contact_spec.rb
> +  # end
Why is this commented out?

2016-10-31 22:44 UTC, andela-fadebayo commented on app/models/service.rb
> +  def self.pending_requests(current_user)
This is not tested

2016-11-01 10:55 UTC, andela-vkironde commented on app/views/notifications/index.html.erb
> +              <%if object.notifiable_type == 'Quote'%>
```Quote``` here refers to a class name and should therefore be uppercase.

2016-11-01 10:56 UTC, andela-vkironde commented on app/views/notifications/index.html.erb
> -          <%#= render partial: "show_information" %>
Done

2016-11-01 10:57 UTC, victor-kironde commented on app/views/notifications/index.html.erb
> +                  <button id='quote_accept' class="btn teal modal-action" onclick="quotation('accepted',<%=object.notifiable.id%>)">Accept</button>
Done

2016-11-01 13:10 UTC, andela-vkironde commented on spec/features/share_contact_spec.rb
> +  # end
It was a feature test expecting a tasker to view an artisan's contact information before accepting or rejecting a quote.

2016-11-16 16:15 UTC, andela-fadebayo approved these changes

2016-11-16 16:16 UTC, merged